### ISSUE TITLE
track addtional fields

### ISSUE THREAD

**Issue by rjfarmer** [wmwolf/MESATestHub#3]
Hi,
Would it be possible to track number of steps, retries and backups for each test case? This can help show us when changes to the code force a model to evolve into regions with bad derivatives/other evolution difficulties.

Thanks
Rob

**Comment by wmwolf** [comment]
Fortunately this feature is already baked in. Each test case can track up to 10 data fields. Right now, no test case is using it though, because submitting the results via the api is a bit more tricky. I'll look into implementing this in mesa_test.

Are we always guaranteed to have retries and backups in every history file? If so, I'll make all test cases track all three of these on the site.

Secondly, is the place we would find these data always the same? I.e. is there always a file called history.data inside a directory called LOGS that has the right columns?

I can make star test cases behave differently than binary test cases, but going beyond that starts to be very complicated.

**Comment by rjfarmer** [comment]
I'm not sure if we always have them in the LOGS file, but i think it gets picked out of the terminal output by the same script that looks for the test string to see if we have passed the test. I know it gets printed when we run each_test_run_and_diff though i'd need to check what happens with each_test_run

**Comment by wmwolf** [comment]
Ok, I'll look at test output and see if there's some consistency. If there's a consistent way to find this data, I agree that we should start tracking it ASAP.

**Comment by wmwolf** [comment]
A partial piece of this is now implemented in that the lines from the output that give runtime, steps, retries, and backups are now saved as a text object and uploaded. Identifying single values for these is nontrivial since some test cases use multiple inlists that may or may not reset the step number, and restarts cause confusing data.

In any case, this repo is moved, so if/when we need more precise data tracking, reopen the issue over on MESAHub. (The repo couldn't be simply moved due to some bad git work on my behalf, so the issues remain on this defunct repo.)
